-- Migración para asegurar columnas necesarias en tabla cliente
-- Ejecutar en Supabase SQL editor

BEGIN;

-- NOTA: Este script NO cambia tipos de columnas usadas por RLS directamente.
-- Aplica estrategia segura con columnas "gemelas" para evitar romper políticas.

-- 1) Asegurar tabla existe (no crea nueva estructura incompatible)
CREATE TABLE IF NOT EXISTS public.cliente (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
);

-- 2) Asegurar columnas base (sin tocar tipos existentes)
ALTER TABLE public.cliente ADD COLUMN IF NOT EXISTS user_id text; -- si ya es uuid, no se modifica aquí
ALTER TABLE public.cliente ADD COLUMN IF NOT EXISTS correo_cliente text;
-- Hash opcional del correo (nullable) para privacidad/deduplicación
ALTER TABLE public.cliente ADD COLUMN IF NOT EXISTS correo_cliente_hash text;
ALTER TABLE public.cliente ADD COLUMN IF NOT EXISTS ci_cliente text;
ALTER TABLE public.cliente ADD COLUMN IF NOT EXISTS nombre_cliente text;
ALTER TABLE public.cliente ADD COLUMN IF NOT EXISTS primer_apellido text;
ALTER TABLE public.cliente ADD COLUMN IF NOT EXISTS segundo_apellido text;
ALTER TABLE public.cliente ADD COLUMN IF NOT EXISTS telefono_cliente text;
ALTER TABLE public.cliente ADD COLUMN IF NOT EXISTS direccion text;
ALTER TABLE public.cliente ADD COLUMN IF NOT EXISTS genero text;
ALTER TABLE public.cliente ADD COLUMN IF NOT EXISTS nit text;
ALTER TABLE public.cliente ADD COLUMN IF NOT EXISTS perfil_completo boolean DEFAULT false;
ALTER TABLE public.cliente ADD COLUMN IF NOT EXISTS foto_url text;
ALTER TABLE public.cliente ADD COLUMN IF NOT EXISTS contrasenia text;
ALTER TABLE public.cliente ADD COLUMN IF NOT EXISTS salt text;
-- Timestamps y fecha de registro automáticos
ALTER TABLE public.cliente ADD COLUMN IF NOT EXISTS fecha_registro date DEFAULT CURRENT_DATE;


-- 3) Índices seguros (no cambian tipos)
CREATE UNIQUE INDEX IF NOT EXISTS cliente_ci_unico ON public.cliente (ci_cliente);
CREATE UNIQUE INDEX IF NOT EXISTS cliente_user_unico ON public.cliente (user_id);
-- Índice único parcial para el hash (solo aplica cuando no es NULL)
DO $$
BEGIN
  -- Crear índice único parcial solo si la columna existe
  IF EXISTS (
    SELECT 1 FROM pg_attribute a
    JOIN pg_class c ON a.attrelid = c.oid
    JOIN pg_namespace n ON c.relnamespace = n.oid
    WHERE n.nspname = 'public' AND c.relname = 'cliente' AND a.attname = 'correo_cliente_hash'
  ) THEN
    IF NOT EXISTS (
      SELECT 1 FROM pg_indexes WHERE schemaname = 'public' AND indexname = 'cliente_correo_hash_unico'
    ) THEN
      EXECUTE 'CREATE UNIQUE INDEX cliente_correo_hash_unico ON public.cliente (correo_cliente_hash) WHERE correo_cliente_hash IS NOT NULL';
    END IF;
  END IF;
END$$;

-- 4) Nota: No se crean columnas gemelas; ajusta tipos directamente en columnas NO usadas por RLS.

-- Ejemplo: migrar user_id a uuid sin romper RLS
-- ALTER TABLE public.cliente ADD COLUMN IF NOT EXISTS user_id_uuid uuid;
-- UPDATE public.cliente SET user_id_uuid = NULLIF(user_id, '')::uuid WHERE user_id IS NOT NULL;
-- CREATE UNIQUE INDEX IF NOT EXISTS cliente_user_unico_uuid ON public.cliente (user_id_uuid);
-- -- Aquí debes recrear las políticas RLS para usar user_id_uuid en lugar de user_id
-- -- Luego, en una ventana de mantenimiento, haz el switch:
-- -- ALTER TABLE public.cliente DROP COLUMN user_id;
-- -- ALTER TABLE public.cliente RENAME COLUMN user_id_uuid TO user_id;

-- Si necesitas ampliar longitud de campos no referenciados por RLS (p. ej.,
-- contrasenia, salt, foto_url, direccion, correo_cliente, nit), cámbialos a text:
-- ALTER TABLE public.cliente ALTER COLUMN contrasenia TYPE text;
-- ALTER TABLE public.cliente ALTER COLUMN salt TYPE text;
-- ALTER TABLE public.cliente ALTER COLUMN foto_url TYPE text;
-- ALTER TABLE public.cliente ALTER COLUMN direccion TYPE text;
-- ALTER TABLE public.cliente ALTER COLUMN correo_cliente TYPE text;
-- ALTER TABLE public.cliente ALTER COLUMN nit TYPE text;

-- Nota sobre correo_cliente_hash:
-- - Permanece NULL por defecto para evitar problemas con flujos existentes.
-- - Si se usa, normaliza el correo (lower/trim) antes del hash.
-- - Recomendado SHA-256 con pepper del servidor; el índice parcial evita obligar su población.

COMMIT;

-- Guía breve:
-- - Si RLS bloquea ALTER TYPE, usa columnas gemelas y recrea políticas apuntando a las nuevas.
-- - No cambies tipos directamente en columnas usadas por RLS.
-- - Valida en staging y haz el switch final (rename) en una ventana corta.
